### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by baticodes** [bradfrost/gatsby-style-guide-guide#1]
I'm not able to install the package via yarn.
After cloning the repository and running "yarn" at the root of the project I receive this error:

```
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error aws-cloudfront-invalidate@0.1.3: The engine "node" is incompatible with this module. Expected version "^6.3.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Using node 8.11.1, yarn 1.7.0, mac os x 10.13.5 high sierra.

Should I switch to node 6?

**Comment by frostyweather** [comment]
@xBau I don't even think we are using that (from another project). So I am going to try and remove that and then you can try cloning the repo again. I'll let ya know. Thanks!

**Comment by brendan-vincent-rice** [comment]
I was getting a similar error. I tried removing "aws-cloudfront-invalidate" then running "yarn" seemed to work fine. However, I get the following errors when running "yarn start": 

![image](https://user-images.githubusercontent.com/835284/41419018-05969c4a-6fbf-11e8-8294-cdd65433db4f.png)

**Comment by frostyweather** [comment]
@xBau The new repo is good to clone now. Hopefully this solves your issue

**Comment by frostyweather** [comment]
@gobrendan Try removing your cache. and then run `yarn start` again. Let me know what you get. Thanks!

**Comment by baticodes** [comment]
@frostyweather Now it works like a charm!

**Comment by frostyweather** [comment]
@xBau Fantastic! Glad to hear it. Thanks for bringing that up so I could get rid of that issue. Appreciate it!

**Comment by brendan-vincent-rice** [comment]
@frostyweather I removed .cache and node_modules, ran yard and all went OK. When I run `yarn install`, I get a similar (maybe the same) error. Should I open a new Issue? Thanks man!

![image](https://user-images.githubusercontent.com/835284/41424710-d47113a8-6fcc-11e8-8e92-864efb5b2ad1.png)

**Comment by frostyweather** [comment]
@gobrendan Try running `npm install`, clear your `.cache` and  `public` folders then run `yarn start` again. If that doesn't work, then we will open an issue. Thanks

**Comment by brendan-vincent-rice** [comment]
Ah, same errors. I'll open a new issue. Thanks!

**Comment by Sarah86** [comment]
Same errors here and I am completely blocked... already tried everything told in stackoverflow
