### ISSUE TITLE
Example with Pattern Lab?

### ISSUE THREAD

**Issue by bessfernandez** [bradfrost/gatsby-style-guide-guide#10]
The Style Guide Guide is great and have enjoyed playing around with it. It is still a bit unclear to me how to consume components from elsewhere (or Pattern Lab as the docs state). Though familiar with Storybook and other tools I am newer to Gatsby so may be missing some pieces..  Is there still an effort underway to demo that or a blog post I may have missed? Thanks!

**Comment by bradfrost** [comment]
@bessfernandez hey there, we're currently doing a lot of work on a client project that has us consuming design system React components. When our project is over we are hoping to merge that stuff into this project. Also, I'd ignore references to Pattern Lab in this project; that's left over from the non-Gatsby version of this project. Sorry about that. 

A few things in the meantime:

1. You can create your design system components and publish the component library on npm, similar to projects like [Material UI](https://material-ui.com/getting-started/installation/) or [Carbon](https://www.npmjs.com/package/carbon-components-react)
2. You can then install those components in your Gatsby project using `npm install your-design-system`
3. You can now reference those components in your project, like `import Button from your-design-system/Button`

There are other ways of getting components into the project, and displaying them in the component page, but for now that's what I would recommend.

**Comment by bessfernandez** [comment]
Thanks so much @bradfrost! I figured those steps as much - but with less Gatsby expertise I was second guessing the internal pieces and was hoping to scope out a further demo. But totally makes sense! Definitely feel like I'm on my way there with Style Guide Guide + my own component library (using Storybook as well). Definitely fun :)
